### PR TITLE
Items & Chests are saved in the cookies

### PR DESCRIPTION
**Pull request by aurelien-defossez**
For players that do not play a randomizer in one session (like me), saving the tracked items & chests is essential.

I stored the items, chests & dungeon chests in the cookies by default, so if the user comes back another day, his progress is saved.

To reset the tracker, I added a "Reset Tracker" command in the settings.

### CODE REVIEW

**Comment by aurelien-defossez** [comment]
You can test it here: https://aurelien-defossez.github.io/oot-tracker/

**Comment by TestRunnerSRL** [comment]
Seems fine. My only caution is that this greatly increases the cookie size. When I checked everything, the cookie is 2947 bytes, and there's a limit of 4093. So it's fine for now. But if many locations and items are added (such as skulltulas) it might become an issue. For now it's fine, but in the future if it becomes a problem and add a ton of things to save we might want to think of a more compressed way to store this.

**Comment by aurelien-defossez** [comment]
I didn't think about that.

Fortunately, the size of the structures I added is constant, it always saves everything and the data type doesn't change.

If we someday have an issue with that, we could either use a second cookie (or more), or compress this indeed. Skulltulas (and gossip stones?) would indeed be interesting to have.

**Comment by TestRunnerSRL** [comment]
Having more cookies uses the same space, so that wouldn't help. The cookie is just a string, so things like false is one more byte than true, etc. There are many ways to store the data in less space, since JSON string is basically the worst option, it's just a lot easier. But we can cross that bridge when we get there. You can also store thing with localdata, but not sure that's supported by browsers as much and is kinda not something i'd want to use if it can be helped

**Pull request merged**
